name: myenv
channels:
  - conda-forge
dependencies:
  - pangeo-notebook==2021.02.07
  - jupyter-panel-proxy
  - xarray
  - zarr
  - intake
  - intake-xarray
  - hvplot
  - panel
  - fsspec
  - s3fs
  - cmocean
